basic.naturalnumber: 1
basic.decimalnumber: 1.0
basic.message: message
basic.choice: false
basic.several.naturalnumbers: 1,2,3,4,5
basic.several.decimalnumbers: 1.0,2.0,3.0,4.0,5.0
basic.several.words: wordOne,wordTwo,wordThree
basic.several.choices: true,false,true,false

